version: 2
models:
  -name: mrt_dim_customers
  description:"Core dimention model for customer analytics. Combines customer profit data, subscription status and aggregated invoices metrics."
  columns:
    -name: customer_id
    description:"Primary key for the  customers,Sources from the stripe."
    test:
      - unique
      - not null

    -name: subscription_id
    description: "Foreign key referencing the customer's active subscription ID"

    -name: total_invoices_issued
    description: "Total count of invoices issued to the customers"

    -name: total_revenue_paid
    description: "Total sum of successfully paid invoice amounts (`payment_status = 'paid'`). Coalesced to 0.00 if no invoices exist."

    -name: last_payment_date
    description: "Timestamp of the customer's most recent successful invoice payment."